# Best dogs in show ( UK, USA)

In [1]:
import pandas as pd

Importing winning dog tables from Wikipedia from the National Dog Show and Westminster Dog Show

In [5]:
#Westminster URL
w_url = 'https://en.wikipedia.org/wiki/List_of_Best_in_Show_winners_of_the_Westminster_Kennel_Club_Dog_Show'

In [6]:
#National show URL 
n_url = "https://en.wikipedia.org/wiki/National_Dog_Show"

### Westminster dog show

In [7]:
# Use Panda's `read_html` to parse the url
### BEGIN SOLUTION
tables = pd.read_html(w_url)
tables

[  Best in Show of the Westminster Kennel Club Dog Show  \
 0  Sussex Spaniel Clussexx Three D Grinchy Glee b...
 1                                            Country
 2                                       Presented by
 3                                      First awarded
 4                                  Currently held by
 5                                            Website

   Best in Show of the Westminster Kennel Club Dog Show.1
 0  Sussex Spaniel Clussexx Three D Grinchy Glee b...
 1                                      United States
 2                            Westminster Kennel Club
 3                                               1907
 4  GCHP Stone Run Afternoon Tea (Poodle (Standard...
 5                            Westminster Kennel Club      ,
      Year                                       Winner  \
 0    1907                            Ch. Warren Remedy
 1    1908                            Ch. Warren Remedy
 2    1909                            Ch. Warren Remedy
 3    1910                           Ch. Sabine Rarebit
 4    1911                           Ch. Tickle Em Jock
 ..    ...                                          ...
 109  2016  GCH Vjk-Myst Garbonita's California Journey
 110  2017                             GCH Rumor Has It
 111  2018  GCHP Belle Creek's All I Care About Is Love
 112  2019           GCHB CH Kingarthur Van Foliny Home
 113  2020                 GCHP Stone Run Afternoon Tea

                           Image                         Breed         Group  \
 0                           NaN          Fox Terrier (Smooth)       Terrier
 1                           NaN          Fox Terrier (Smooth)       Terrier
 2                           NaN          Fox Terrier (Smooth)       Terrier
 3                           NaN          Fox Terrier (Smooth)       Terrier
 4                           NaN              Scottish Terrier       Terrier
 ..                          ...                           ...           ...
 109  2016 Westminister Dog Show  Pointer (German Shorthaired)      Sporting
 110                         NaN               German Shepherd       Herding
 111                         NaN                  Bichon Frise  Non-Sporting
 112                         NaN            Fox Terrier (Wire)       Terrier
 113                         NaN             Poodle (Standard)  Non-Sporting

                                                  Owner    Ref(s)
 0                                  Winthrop Rutherfurd      [15]
 1                                  Winthrop Rutherfurd      [16]
 2                                  Winthrop Rutherfurd      [16]
 3                                        F. H. Farwell  [19][20]
 4                                      A. Albright Jr.      [21]
 ..                                                 ...       ...
 109  Valerie Atkinson & Alice Manning & Yvonne Hass...     [104]
 110                                        Kent Boyles     [105]
 111  Patrina Odette, Bruce Odette, Lindsay Van Keur...     [106]
 112                                 Victor Malzoni Jr.     [107]
 113                                Connie Unger, W Lee       NaN

 [114 rows x 7 columns],
    Number of winners                                              Breed
 0                 15                                   Wire Fox Terrier
 1                  8                                   Scottish Terrier
 2                  6                           English Springer Spaniel
 3                  5                                    Standard Poodle
 4                  4  Airedale Terrier, American Cocker Spaniel,[B] ...
 5                  3  Miniature Poodle, Pointer, German Shorthaired ...
 6                  2  Afghan Hound, Beagle, Bichon Frise, Bulldog, B...
 7                  1  Affenpinscher, Bedlington Terrier, Clumber Spa...,
    Number of winners         Group
 0                 47       Terrier
 1                 18      Sporting
 2                 15    Working[D]
 3                 11           Toy
 4                 11  Non-sporting
 5                  6         Hound
 6                  3       Herding]

In [9]:
df = tables[1]
df.columns = ['year', 'winner', 'image', 'breed', 'group', 'owner', 'ref(s)']
df.head()

,year,winner,image,breed,group,owner,ref(s)
0,1907,Ch. Warren Remedy,NaN,Fox Terrier (Smooth),Terrier,Winthrop Rutherfurd,[15]
1,1908,Ch. Warren Remedy,NaN,Fox Terrier (Smooth),Terrier,Winthrop Rutherfurd,[16]
2,1909,Ch. Warren Remedy,NaN,Fox Terrier (Smooth),Terrier,Winthrop Rutherfurd,[16]
3,1910,Ch. Sabine Rarebit,NaN,Fox Terrier (Smooth),Terrier,F. H. Farwell,[19][20]
4,1911,Ch. Tickle Em Jock,NaN,Scottish Terrier,Terrier,A. Albright Jr.,[21]

In [17]:
W_dogs= df.filter(['year','winner','breed'])
W_dogs.head()

   year              winner                 breed
0  1907   Ch. Warren Remedy  Fox Terrier (Smooth)
1  1908   Ch. Warren Remedy  Fox Terrier (Smooth)
2  1909   Ch. Warren Remedy  Fox Terrier (Smooth)
3  1910  Ch. Sabine Rarebit  Fox Terrier (Smooth)
4  1911  Ch. Tickle Em Jock      Scottish Terrier

### National Dog Show

In [38]:
W_dogs.value_counts("breed")

breed
Fox Terrier (Wire)              15
Scottish Terrier                 8
Spaniel (English Springer)       6
Poodle (Standard)                5
Sealyham Terrier                 4
Pekingese                        4
Airedale Terrier                 4
Fox Terrier (Smooth)             4
Boxer                            4
Doberman Pinscher                4
Pointer (German Shorthaired)     3
Poodle (Miniature)               3
Pointer                          3
Bulldog                          2
Bichon Frise                     2
Norwich Terrier                  2
Old English Sheepdog             2
West Highland White Terrier      2
Afghan Hound                     2
Beagle (15 Inch)                 2
Poodle (Toy)                     2
Spaniel (Cocker) Black[B]        2
Lakeland Terrier                 2
Newfoundland                     2
Bedlington Terrier               1
Collie (Rough)                   1
German Shepherd                  1
Bull Terrier (Colored)           1
German Shepherd Dog              1
Bull Terrier (White)             1
Kerry Blue Terrier               1
Yorkshire Terrier                1
Not awarded                      1
Spaniel (Clumber)                1
Welsh Terrier                    1
Sussex Spaniel                   1
Standard Schnauzer               1
Spaniel (Irish Water)            1
Spaniel (Cocker) Parti[B]        1
Spaniel (Cocker) ASCOB[B]        1
Skye Terrier                     1
Papillon                         1
Siberian Husky                   1
Setter (English)                 1
Scottish Deerhound               1
Pug                              1
Pomeranian                       1
Whippet                          1
Affenpinscher                    1
dtype: int64

In [18]:
# Use Panda's `read_html` to parse the url
### BEGIN SOLUTION
tables = pd.read_html(n_url)
tables

[                            National Dog Show  \
 0                                         NaN
 1                               Also known as
 2                                       Genre
 3                                  Created by
 4                                Presented by
 5                                      Judges
 6                           Country of origin
 7                                  Production
 8                        Production locations
 9                                Running time
 10                                Distributor
 11                                    Release
 12                           Original network
 13                           Original release
 14                             External links
 15   The Kennel Club of Philadelphia Dog Show
 16  The National Dog Show Presented by Purina

                                   National Dog Show.1
 0                                                 NaN
 1           The National Dog Show Presented by Purina
 2                                            Dog show
 3                   Kennel Club of Philadelphia (KCP)
 4                             John O'HurleyDavid Frei
 5               Frank DePaulo (Show Chairman & Judge)
 6                                       United States
 7                                          Production
 8   Greater Philadelphia Expo Center at Oaks in Oa...
 9                                             2 hours
 10                             NBC Sports Productions
 11                                            Release
 12                                                NBC
 13                        November 2002; 18 years ago
 14                                     External links
 15           The Kennel Club of Philadelphia Dog Show
 16          The National Dog Show Presented by Purina  ,
     Year                 Breed                                  Name  \
 0   2001    Labrador Retriever                        Gustavus Brady
 1   2002       Standard Poodle             Ale Kai Mikimoto On Fifth
 2   2003              Doberman                Blue Chip Purple Reign
 3   2004    Smooth Fox Terrier              Aimhi Avalon Renaissance
 4   2005  Colored Bull Terrier              Rocky Top's Sundance Kid
 5   2006            Toy Poodle                Smash JP Win A Victory
 6   2007   Australian Shepherd         Buff Cap Creslane Arctic Mist
 7   2008               Pointer         Cookieland Seasyde Hollyberry
 8   2009      Scottish Terrier    Ch. Roundtown Mercedes of Maryscot
 9   2010          Irish Setter                 Windntide Mr. Sandman
 10  2011      Wire Fox Terrier                 GCH Steele Your Heart
 11  2012      Wire Fox Terrier             Afterall Painting the Sky
 12  2013     American Foxhound           Gch. Kiarry's Pandora's Box
 13  2014            Bloodhound       Flessner's International S’cess
 14  2015          Skye Terrier    GCH CH Cragsmoor Good Time Charlie
 15  2016             Greyhound         GCHS CH Grandcru Giaconda CGC
 16  2017      Brussels Griffon          GCH Somerset Wynzall Hashtag
 17  2018               Whippet       GCHG Pinnacle Tennessee Whiskey
 18  2019               Bulldog  GCHG Diamond Gold Majesu Pisko Bulls
 19  2020    Scottish Deerhound   GCH Foxcliffe Claire Randall Fraser

    Call Name          Owner/Trainer Reference
 0        Gus                    NaN       NaN
 1       Miki           Karen LeFrak       NaN
 2     Raisin                    NaN       NaN
 3     Gracie                    NaN       [6]
 4      Rufus         Barbara Bishop       [7]
 5      Vikki             Kaz Hosaka       [6]
 6    Swizzle           Nancy Gagnon       [8]
 7      Holly  Sean & Tammy McCarthy       [9]
 8      Sadie          Amelia Musser       [6]
 9    Clooney           Peter Kubacz      [10]
 10      Eira         Gabriel Rangel       NaN
 11       Sky         Gabriel Rangel      [11]
 12     Jewel            Lisa Miller      [12]
 13    Nathan         Heather Helmer      [13]
 14   Charlie                    NaN      [14]
 15       Gia         Melanie Steele      [15]
 16    Newton         Keith Jacobson      [16]
 17   Whiskey         Justin Smithey      [17]
 18      Thor          Eduardo Paris  [18][19]
 19    Claire           Angela Lloyd      [20]  ,
    .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}.mw-parser-output .infobox .navbar{font-size:100%}.mw-parser-output .navbox .navbar{display:block;font-size:100%}.mw-parser-output .navbox-title .navbar{float:left;text-align:left;margin-right:0.5em}vteThanksgiving  \
 0                               History andtraditions
 1                                              Canada
 2                                       United States
 3                                             Cuisine
 4                                               Songs
 5                                    Associatedevents
 6                                            Cultural
 7                                             Parades
 8                                            Protests
 9                                              Sports
 10                                           Football
 11                                         Basketball
 12                                       Turkey Trots
 13                                             Others

    .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}.mw-parser-output .infobox .navbar{font-size:100%}.mw-parser-output .navbox .navbar{display:block;font-size:100%}.mw-parser-output .navbox-title .navbar{float:left;text-align:left;margin-right:0.5em}vteThanksgiving.1
 0   Canada Samuel de Champlain Martin Frobisher Ha...
 1   Samuel de Champlain Martin Frobisher Halifax F...
 2   Pilgrims Mayflower Plymouth Colony Plymouth, M...
 3   Thanksgiving dinner Turkey Deep-fried Tofurkey...
 4   "Alice's Restaurant" "Bless This House" "Bring...
 5   Cultural Christmas and holiday season Harvest ...
 6   Christmas and holiday season Harvest festivals...
 7   Novant Health (Charlotte) Chicago America's (D...
 8   National Day of Mourning Unthanksgiving Day Bu...
 9   Football NFL on Thanksgiving Day CFL Thanksgiv...
 10  NFL on Thanksgiving Day CFL Thanksgiving Class...
 11  AdvoCare Invitational Battle 4 Atlantis Wooden...
 12  Berwick Run for the Diamonds Buffalo Turkey Tr...
 13  National Dog Show Pumpkin chucking Turkey bowl...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ,
                0                                                  1
 0         Canada  Samuel de Champlain Martin Frobisher Halifax F...
 1  United States  Pilgrims Mayflower Plymouth Colony Plymouth, M...
 2        Cuisine  Thanksgiving dinner Turkey Deep-fried Tofurkey...
 3          Songs  "Alice's Restaurant" "Bless This House" "Bring...,
           0                                                  1
 0  Cultural  Christmas and holiday season Harvest festivals...
 1   Parades  Novant Health (Charlotte) Chicago America's (D...
 2  Protests  National Day of Mourning Unthanksgiving Day Bu...,
               0                                                  1
 0      Football  NFL on Thanksgiving Day CFL Thanksgiving Class...
 1    Basketball  AdvoCare Invitational Battle 4 Atlantis Wooden...
 2  Turkey Trots  Berwick Run for the Diamonds Buffalo Turkey Tr...
 3        Others  National Dog Show Pumpkin chucking Turkey bowl...]

In [20]:
df_2 = tables[1]
df_2.columns = ['year', 'breed', 'name', 'call name', 'owner/trainer', 'reference']
df_2.head()

,year,breed,name,call name,owner/trainer,reference
0,2001,Labrador Retriever,Gustavus Brady,Gus,NaN,NaN
1,2002,Standard Poodle,Ale Kai Mikimoto On Fifth,Miki,Karen LeFrak,NaN
2,2003,Doberman,Blue Chip Purple Reign,Raisin,NaN,NaN
3,2004,Smooth Fox Terrier,Aimhi Avalon Renaissance,Gracie,NaN,[6]
4,2005,Colored Bull Terrier,Rocky Top's Sundance Kid,Rufus,Barbara Bishop,[7]

In [23]:
N_dogs= df_2.filter(['year','name','breed'])
N_dogs.head()

   year                       name                 breed
0  2001             Gustavus Brady    Labrador Retriever
1  2002  Ale Kai Mikimoto On Fifth       Standard Poodle
2  2003     Blue Chip Purple Reign              Doberman
3  2004   Aimhi Avalon Renaissance    Smooth Fox Terrier
4  2005   Rocky Top's Sundance Kid  Colored Bull Terrier

In [41]:
N_dogs.rename(columns ={"name":"winner"})

    year                                winner                 breed
0   2001                        Gustavus Brady    Labrador Retriever
1   2002             Ale Kai Mikimoto On Fifth       Standard Poodle
2   2003                Blue Chip Purple Reign              Doberman
3   2004              Aimhi Avalon Renaissance    Smooth Fox Terrier
4   2005              Rocky Top's Sundance Kid  Colored Bull Terrier
5   2006                Smash JP Win A Victory            Toy Poodle
6   2007         Buff Cap Creslane Arctic Mist   Australian Shepherd
7   2008         Cookieland Seasyde Hollyberry               Pointer
8   2009    Ch. Roundtown Mercedes of Maryscot      Scottish Terrier
9   2010                 Windntide Mr. Sandman          Irish Setter
10  2011                 GCH Steele Your Heart      Wire Fox Terrier
11  2012             Afterall Painting the Sky      Wire Fox Terrier
12  2013           Gch. Kiarry's Pandora's Box     American Foxhound
13  2014       Flessner's International S’cess            Bloodhound
14  2015    GCH CH Cragsmoor Good Time Charlie          Skye Terrier
15  2016         GCHS CH Grandcru Giaconda CGC             Greyhound
16  2017          GCH Somerset Wynzall Hashtag      Brussels Griffon
17  2018       GCHG Pinnacle Tennessee Whiskey               Whippet
18  2019  GCHG Diamond Gold Majesu Pisko Bulls               Bulldog
19  2020   GCH Foxcliffe Claire Randall Fraser    Scottish Deerhound

In [36]:
N_dogs.value_counts('breed')

breed
Wire Fox Terrier        2
Irish Setter            1
Australian Shepherd     1
Bloodhound              1
Brussels Griffon        1
Bulldog                 1
Colored Bull Terrier    1
Doberman                1
Greyhound               1
Labrador Retriever      1
Whippet                 1
Pointer                 1
Scottish Deerhound      1
Scottish Terrier        1
Skye Terrier            1
Smooth Fox Terrier      1
Standard Poodle         1
Toy Poodle              1
American Foxhound       1
dtype: int64